export type CommercialTarget = {
  active?: boolean;
  service: "ontstoppingen";
  keyword: "ontstoppingsdienst" | "wc-verstopt" | "riool-ontstoppen" | "afvoer-ontstoppen";
  city: string;
  title?: string;
  priority?: number;
  score?: number;
  source: "manual-phase1" | "ads" | "ads+analytics";
};

export const COMMERCIAL_TARGETS: CommercialTarget[] = [
  {
    active: true,
    service: "ontstoppingen",
    keyword: "ontstoppingsdienst",
    city: "Aartselaar",
    title: "Ontstoppingsdienst in Aartselaar",
    priority: 90,
    score: 90,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "ontstoppingsdienst",
    city: "Antwerpen",
    title: "Ontstoppingsdienst in Antwerpen",
    priority: 95,
    score: 95,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "ontstoppingsdienst",
    city: "Beveren",
    title: "Ontstoppingsdienst in Beveren",
    priority: 82,
    score: 82,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "ontstoppingsdienst",
    city: "Boom",
    title: "Ontstoppingsdienst in Boom",
    priority: 94,
    score: 94,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "ontstoppingsdienst",
    city: "Lier",
    title: "Ontstoppingsdienst in Lier",
    priority: 84,
    score: 84,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "ontstoppingsdienst",
    city: "Mechelen",
    title: "Ontstoppingsdienst in Mechelen",
    priority: 93,
    score: 93,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "ontstoppingsdienst",
    city: "Niel",
    title: "Ontstoppingsdienst in Niel",
    priority: 88,
    score: 88,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "ontstoppingsdienst",
    city: "Rumst",
    title: "Ontstoppingsdienst in Rumst",
    priority: 86,
    score: 86,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "ontstoppingsdienst",
    city: "Schelle",
    title: "Ontstoppingsdienst in Schelle",
    priority: 87,
    score: 87,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "ontstoppingsdienst",
    city: "Willebroek",
    title: "Ontstoppingsdienst in Willebroek",
    priority: 89,
    score: 89,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "wc-verstopt",
    city: "Aartselaar",
    title: "WC verstopt in Aartselaar",
    priority: 78,
    score: 78,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "wc-verstopt",
    city: "Antwerpen",
    title: "WC verstopt in Antwerpen",
    priority: 91,
    score: 91,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "wc-verstopt",
    city: "Boom",
    title: "WC verstopt in Boom",
    priority: 85,
    score: 85,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "wc-verstopt",
    city: "Mechelen",
    title: "WC verstopt in Mechelen",
    priority: 89,
    score: 89,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "wc-verstopt",
    city: "Niel",
    title: "WC verstopt in Niel",
    priority: 80,
    score: 80,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "wc-verstopt",
    city: "Rumst",
    title: "WC verstopt in Rumst",
    priority: 79,
    score: 79,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "wc-verstopt",
    city: "Schelle",
    title: "WC verstopt in Schelle",
    priority: 79,
    score: 79,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "wc-verstopt",
    city: "Willebroek",
    title: "WC verstopt in Willebroek",
    priority: 81,
    score: 81,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "riool-ontstoppen",
    city: "Antwerpen",
    title: "Riool ontstoppen in Antwerpen",
    priority: 88,
    score: 88,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "riool-ontstoppen",
    city: "Boom",
    title: "Riool ontstoppen in Boom",
    priority: 83,
    score: 83,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "riool-ontstoppen",
    city: "Mechelen",
    title: "Riool ontstoppen in Mechelen",
    priority: 87,
    score: 87,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "riool-ontstoppen",
    city: "Willebroek",
    title: "Riool ontstoppen in Willebroek",
    priority: 80,
    score: 80,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "afvoer-ontstoppen",
    city: "Antwerpen",
    title: "Afvoer ontstoppen in Antwerpen",
    priority: 84,
    score: 84,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "afvoer-ontstoppen",
    city: "Boom",
    title: "Afvoer ontstoppen in Boom",
    priority: 81,
    score: 81,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "afvoer-ontstoppen",
    city: "Mechelen",
    title: "Afvoer ontstoppen in Mechelen",
    priority: 85,
    score: 85,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "afvoer-ontstoppen",
    city: "Niel",
    title: "Afvoer ontstoppen in Niel",
    priority: 76,
    score: 76,
    source: "manual-phase1",
  },
];