export type CommercialTarget = {
  active?: boolean;
  service: "ontstoppingen";
  keyword: "ontstoppingsdienst" | "wc-verstopt" | "riool-ontstoppen" | "afvoer-ontstoppen";
  city: string;
  title?: string;
  priority?: number;
  score?: number;
  source: "manual-phase1" | "ads" | "ads+analytics";
};

export const COMMERCIAL_TARGETS: CommercialTarget[] = [
  {
    active: true,
    service: "ontstoppingen",
    keyword: "ontstoppingsdienst",
    city: "Aartselaar",
    title: "Ontstoppingsdienst in Aartselaar",
    priority: 90,
    score: 90,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "ontstoppingsdienst",
    city: "Antwerpen",
    title: "Ontstoppingsdienst in Antwerpen",
    priority: 95,
    score: 95,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "ontstoppingsdienst",
    city: "Beveren",
    title: "Ontstoppingsdienst in Beveren",
    priority: 82,
    score: 82,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "ontstoppingsdienst",
    city: "Boom",
    title: "Ontstoppingsdienst in Boom",
    priority: 94,
    score: 94,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "ontstoppingsdienst",
    city: "Lier",
    title: "Ontstoppingsdienst in Lier",
    priority: 84,
    score: 84,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "ontstoppingsdienst",
    city: "Mechelen",
    title: "Ontstoppingsdienst in Mechelen",
    priority: 93,
    score: 93,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "ontstoppingsdienst",
    city: "Niel",
    title: "Ontstoppingsdienst in Niel",
    priority: 88,
    score: 88,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "ontstoppingsdienst",
    city: "Rumst",
    title: "Ontstoppingsdienst in Rumst",
    priority: 86,
    score: 86,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "ontstoppingsdienst",
    city: "Schelle",
    title: "Ontstoppingsdienst in Schelle",
    priority: 87,
    score: 87,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "ontstoppingsdienst",
    city: "Willebroek",
    title: "Ontstoppingsdienst in Willebroek",
    priority: 89,
    score: 89,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "wc-verstopt",
    city: "Aartselaar",
    title: "WC verstopt in Aartselaar",
    priority: 78,
    score: 78,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "wc-verstopt",
    city: "Antwerpen",
    title: "WC verstopt in Antwerpen",
    priority: 91,
    score: 91,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "wc-verstopt",
    city: "Boom",
    title: "WC verstopt in Boom",
    priority: 85,
    score: 85,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "wc-verstopt",
    city: "Mechelen",
    title: "WC verstopt in Mechelen",
    priority: 89,
    score: 89,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "wc-verstopt",
    city: "Niel",
    title: "WC verstopt in Niel",
    priority: 80,
    score: 80,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "wc-verstopt",
    city: "Rumst",
    title: "WC verstopt in Rumst",
    priority: 79,
    score: 79,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "wc-verstopt",
    city: "Schelle",
    title: "WC verstopt in Schelle",
    priority: 79,
    score: 79,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "wc-verstopt",
    city: "Willebroek",
    title: "WC verstopt in Willebroek",
    priority: 81,
    score: 81,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "riool-ontstoppen",
    city: "Antwerpen",
    title: "Riool ontstoppen in Antwerpen",
    priority: 88,
    score: 88,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "riool-ontstoppen",
    city: "Boom",
    title: "Riool ontstoppen in Boom",
    priority: 83,
    score: 83,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "riool-ontstoppen",
    city: "Mechelen",
    title: "Riool ontstoppen in Mechelen",
    priority: 87,
    score: 87,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "riool-ontstoppen",
    city: "Willebroek",
    title: "Riool ontstoppen in Willebroek",
    priority: 80,
    score: 80,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "afvoer-ontstoppen",
    city: "Antwerpen",
    title: "Afvoer ontstoppen in Antwerpen",
    priority: 84,
    score: 84,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "afvoer-ontstoppen",
    city: "Boom",
    title: "Afvoer ontstoppen in Boom",
    priority: 81,
    score: 81,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "afvoer-ontstoppen",
    city: "Mechelen",
    title: "Afvoer ontstoppen in Mechelen",
    priority: 85,
    score: 85,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "afvoer-ontstoppen",
    city: "Niel",
    title: "Afvoer ontstoppen in Niel",
    priority: 76,
    score: 76,
    source: "manual-phase1",
  },

  {
    active: true,
    service: "ontstoppingen",
    keyword: "riool-ontstoppen",
    city: "Aartselaar",
    title: "Riool ontstoppen in Aartselaar",
    priority: 80,
    score: 80,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "afvoer-ontstoppen",
    city: "Aartselaar",
    title: "Afvoer ontstoppen in Aartselaar",
    priority: 80,
    score: 80,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "ontstoppingsdienst",
    city: "Bornem",
    title: "Ontstoppingsdienst in Bornem",
    priority: 80,
    score: 80,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "wc-verstopt",
    city: "Bornem",
    title: "WC verstopt in Bornem",
    priority: 80,
    score: 80,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "riool-ontstoppen",
    city: "Bornem",
    title: "Riool ontstoppen in Bornem",
    priority: 80,
    score: 80,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "afvoer-ontstoppen",
    city: "Bornem",
    title: "Afvoer ontstoppen in Bornem",
    priority: 80,
    score: 80,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "ontstoppingsdienst",
    city: "Duffel",
    title: "Ontstoppingsdienst in Duffel",
    priority: 80,
    score: 80,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "wc-verstopt",
    city: "Duffel",
    title: "WC verstopt in Duffel",
    priority: 80,
    score: 80,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "riool-ontstoppen",
    city: "Duffel",
    title: "Riool ontstoppen in Duffel",
    priority: 80,
    score: 80,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "afvoer-ontstoppen",
    city: "Duffel",
    title: "Afvoer ontstoppen in Duffel",
    priority: 80,
    score: 80,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "ontstoppingsdienst",
    city: "Edegem",
    title: "Ontstoppingsdienst in Edegem",
    priority: 80,
    score: 80,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "wc-verstopt",
    city: "Edegem",
    title: "WC verstopt in Edegem",
    priority: 80,
    score: 80,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "riool-ontstoppen",
    city: "Edegem",
    title: "Riool ontstoppen in Edegem",
    priority: 80,
    score: 80,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "afvoer-ontstoppen",
    city: "Edegem",
    title: "Afvoer ontstoppen in Edegem",
    priority: 80,
    score: 80,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "ontstoppingsdienst",
    city: "Hemiksem",
    title: "Ontstoppingsdienst in Hemiksem",
    priority: 80,
    score: 80,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "wc-verstopt",
    city: "Hemiksem",
    title: "WC verstopt in Hemiksem",
    priority: 80,
    score: 80,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "riool-ontstoppen",
    city: "Hemiksem",
    title: "Riool ontstoppen in Hemiksem",
    priority: 80,
    score: 80,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "afvoer-ontstoppen",
    city: "Hemiksem",
    title: "Afvoer ontstoppen in Hemiksem",
    priority: 80,
    score: 80,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "ontstoppingsdienst",
    city: "Hove",
    title: "Ontstoppingsdienst in Hove",
    priority: 80,
    score: 80,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "wc-verstopt",
    city: "Hove",
    title: "WC verstopt in Hove",
    priority: 80,
    score: 80,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "riool-ontstoppen",
    city: "Hove",
    title: "Riool ontstoppen in Hove",
    priority: 80,
    score: 80,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "afvoer-ontstoppen",
    city: "Hove",
    title: "Afvoer ontstoppen in Hove",
    priority: 80,
    score: 80,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "ontstoppingsdienst",
    city: "Kontich",
    title: "Ontstoppingsdienst in Kontich",
    priority: 80,
    score: 80,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "wc-verstopt",
    city: "Kontich",
    title: "WC verstopt in Kontich",
    priority: 80,
    score: 80,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "riool-ontstoppen",
    city: "Kontich",
    title: "Riool ontstoppen in Kontich",
    priority: 80,
    score: 80,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "afvoer-ontstoppen",
    city: "Kontich",
    title: "Afvoer ontstoppen in Kontich",
    priority: 80,
    score: 80,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "ontstoppingsdienst",
    city: "Lint",
    title: "Ontstoppingsdienst in Lint",
    priority: 80,
    score: 80,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "wc-verstopt",
    city: "Lint",
    title: "WC verstopt in Lint",
    priority: 80,
    score: 80,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "riool-ontstoppen",
    city: "Lint",
    title: "Riool ontstoppen in Lint",
    priority: 80,
    score: 80,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "afvoer-ontstoppen",
    city: "Lint",
    title: "Afvoer ontstoppen in Lint",
    priority: 80,
    score: 80,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "ontstoppingsdienst",
    city: "Mortsel",
    title: "Ontstoppingsdienst in Mortsel",
    priority: 80,
    score: 80,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "wc-verstopt",
    city: "Mortsel",
    title: "WC verstopt in Mortsel",
    priority: 80,
    score: 80,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "riool-ontstoppen",
    city: "Mortsel",
    title: "Riool ontstoppen in Mortsel",
    priority: 80,
    score: 80,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "afvoer-ontstoppen",
    city: "Mortsel",
    title: "Afvoer ontstoppen in Mortsel",
    priority: 80,
    score: 80,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "riool-ontstoppen",
    city: "Niel",
    title: "Riool ontstoppen in Niel",
    priority: 80,
    score: 80,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "ontstoppingsdienst",
    city: "Puurs-Sint-Amands",
    title: "Ontstoppingsdienst in Puurs-Sint-Amands",
    priority: 80,
    score: 80,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "wc-verstopt",
    city: "Puurs-Sint-Amands",
    title: "WC verstopt in Puurs-Sint-Amands",
    priority: 80,
    score: 80,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "riool-ontstoppen",
    city: "Puurs-Sint-Amands",
    title: "Riool ontstoppen in Puurs-Sint-Amands",
    priority: 80,
    score: 80,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "afvoer-ontstoppen",
    city: "Puurs-Sint-Amands",
    title: "Afvoer ontstoppen in Puurs-Sint-Amands",
    priority: 80,
    score: 80,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "riool-ontstoppen",
    city: "Rumst",
    title: "Riool ontstoppen in Rumst",
    priority: 80,
    score: 80,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "afvoer-ontstoppen",
    city: "Rumst",
    title: "Afvoer ontstoppen in Rumst",
    priority: 80,
    score: 80,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "riool-ontstoppen",
    city: "Schelle",
    title: "Riool ontstoppen in Schelle",
    priority: 80,
    score: 80,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "afvoer-ontstoppen",
    city: "Schelle",
    title: "Afvoer ontstoppen in Schelle",
    priority: 80,
    score: 80,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "ontstoppingsdienst",
    city: "Temse",
    title: "Ontstoppingsdienst in Temse",
    priority: 80,
    score: 80,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "wc-verstopt",
    city: "Temse",
    title: "WC verstopt in Temse",
    priority: 80,
    score: 80,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "riool-ontstoppen",
    city: "Temse",
    title: "Riool ontstoppen in Temse",
    priority: 80,
    score: 80,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "afvoer-ontstoppen",
    city: "Temse",
    title: "Afvoer ontstoppen in Temse",
    priority: 80,
    score: 80,
    source: "manual-phase1",
  },
  {
    active: true,
    service: "ontstoppingen",
    keyword: "afvoer-ontstoppen",
    city: "Willebroek",
    title: "Afvoer ontstoppen in Willebroek",
    priority: 80,
    score: 80,
    source: "manual-phase1",
  },
];